### 1. 회원가입 폼 성공

POST http://127.0.0.1:9001/user-service/users
Content-Type: application/json
Accept: */*
Connection: keep-alive

{
  "username": "kose",
  "email": "kose@naver.com",
  "password": "kose123456"
}

> {%
    client.test("회원 가입 요청 성공", function() {
        client.assert(response.status === 200, "Response status is OK");
    });
%}


### 2. 모든 회원 조회 성공

GET http://127.0.0.1:9001/user-service/users
Content-Type: application/json
Accept: */*
Connection: keep-alive

> {%
    client.test("모든 회원 조회", function() {
        client.assert(response.status === 200, "Response status is OK");
    });
%}